[tool.poetry]
name = "cmpp"
version = "0.1.0"
description = ""
authors = ["WW18 <wwasil@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
pyqt5 = "^5.15.9"
pyqtgraph = "~0.13.3"
ipykernel = "^6.25.1"
#sympy = "^1.12"
#pyopengl = "^3.1.7"
#pyopengl-accelerate = "^3.1.7"
#lmfit = "^1.2.2"
#scipy = "^1.11.2"
#matplotlib = "^3.7.2"
sympy = "^1.12"
arc-alkali-rydberg-calculator = "^3.3.0"
pyfftw = "^0.13.1"
#numba = "^0.57"
#numpy = "^1.24"
#numba = "^0.57.1"
#numexpr = "^2.8.6"
pathos = "^0.3.1"
xarray = "^2023.9.0"
zarr = "^2.16.1"
numpy = "^1.26.3"
pyopengl = "^3.1.7"
pyopengl-accelerate = "^3.1.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
